std_msgs/Header header
geometry_msgs/Pose goal_pose
autoware_planning_msgs/LaneletSegment[] segments
unique_identifier_msgs/UUID uuid
bool allow_modification
---
autoware_common_msgs/ResponseStatus status
