# Options for shift_mode
uint8 EXPLICIT_LATERAL_OFFSET_AMOUNT = 1
uint8 LATERAL_OFFSET_DIRECTION = 2

# Options for shift_direction_value (used when shift_mode = LATERAL_OFFSET_DIRECTION)
uint8 RESET = 0
uint8 LEFT = 1
uint8 RIGHT = 2

uint8 shift_mode

# When shift_mode = EXPLICIT_LATERAL_OFFSET_AMOUNT:
# Target lateral offset [m], same convention as LateralOffset.msg topic
# positive -> left of the reference path, negative -> right of the reference path
float32 shift_value

# When shift_mode = LATERAL_OFFSET_DIRECTION
uint8 shift_direction_value
---
# response code is propagated from tier4_planning_msgs/srv/SetLateralOffset
uint16 response_code

autoware_common_msgs/ResponseStatus status
