uint16 UNKNOWN = 0
uint16 CANCEL = 1    # Cancel the MRM request.
uint16 DELEGATE = 2  # Delegate the selection of MRM behavior to Autoware.
uint16 BEHAVIOR = 3  # Activate the specified MRM behavior if possible.

uint16 strategy
uint32 behavior      # Used when the strategy field is BEHAVIOR.
---
autoware_common_msgs/ResponseStatus status
